version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: fd2ee12swq
      POSTGRES_USER: postgres
      POSTGRES_DB: dotnet
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    environment:
      RabbitMqConfig__Username: admin
      RabbitMqConfig__Password: 1234
      RabbitMqConfig__Hostname: dotnet_rabbitmq
      ConnectionStrings__Default: "Host=dotnet_postgres;Port=5432;Database=dotnet;Username=postgres;Password=fd2ee12swq"
    build:
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
    
  dotnet_mailing:
    image: dotnet-mailing
    build:
      dockerfile: ./Dotnet.Homeworks.Mailing.API/Dockerfile
    environment:
      RabbitMqConfig__Username: admin
      RabbitMqConfig__Password: 1234
      RabbitMqConfig__Hostname: dotnet_rabbitmq
      EmailConfig__Email: am@dm.ru
      EmailConfig__Host: dm.ru
      EmailConfig__Port: 567
      EmailConfig__Password: 123456
    depends_on:
      - dotnet_rabbitmq
    
  dotnet_storage:
    image: dotnet-web