version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: userPostgres
      POSTGRES_PASSWORD: passwordPostgres
      POSTGRES_DB: dbPostgres
    ports:
      - "5432:5432"
  dotnet_web:
    image: dotnet-web
    environment:
      ConnectionStrings__Default: "Host=localhost;Username=userPostgres;Password=passwordPostgres;Database=dbPostgres"
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - dotnet_postgres